name: datacrime
description: "Projeto Zecchin Analytica - Monitoramento de Crimes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3  # ADICIONE ESTA LINHA (A peça que faltava)
  http: ^1.2.0
  geolocator: ^13.0.0
  geocoding: ^4.0.0
  pointer_interceptor: ^0.10.1+2
  # Você pode manter ou remover estas duas abaixo se não for usar o mapa antigo:
  #flutter_map: ^8.2.0 
  #latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# GAVETA DO FLUTTER (Fica separada das dependencies)
flutter:
  uses-material-design: true