name: Deploy Automático Firebase
on:
  push:
    branches:
      - main # Dispara sempre que você der push na branch principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar Código
        uses: actions/checkout@v4

      - name: 2. Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 3. Instalar Dependências
        run: flutter pub get

      - name: 4. Build Web (Release)
        run: flutter build web --release

      - name: 5. Deploy para o Firebase
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}